In [1]:
import numpy as np
from scipy.optimize import differential_evolution
from scipy.optimize import fmin_bfgs
import scipy

In [2]:
import keras.models

Using TensorFlow backend.


In [3]:
from keras.models import load_model

In [4]:
#Load Model
model = load_model('model4_with_18_new_models_epoch500.hdf5')

In [ ]:
#best model of the 586 models model 305 minimum = 53.41
array([  5.627202,   4.90473 ,   0.826185,   0.30315 ,   2.098165,
        21.395675,  19.387975,  10.1899  ,   9.3509  ,  13.929396,
         4.43708 ,   2.23695 ,   3.34379 ,   1.89416 ,   4.72719 ,
         4.1657  ,   0.535326,   2.231424,   0.27457 ,   0.57916 ,
         4.410275,   4.0934  ,   3.12106 ,   5.367372,   5.897759,
         5.228994,   0.084174,   4.875925,   4.38531 ,   3.00054 ,
         1.454085,   4.075335,   1.616332,   2.23991 ,   4.40025 ,
         1.506965,   0.994074,   3.301525,   1.24586 ,   2.724975,
         4.92365 ,   3.3054  ,  24.892625,  21.6432  ,  16.927768,
         4.494695,   3.489255,   4.23843 ,   2.379335,   3.699805])

array([  (5.627202,5.627202), (4.90473,4.90473),(0.826185,0.826185),   (0.30315,0.30315),   (2.098165,2.098165),
        (21.395675,21.395675), (19.387975,19.387975), (10.1899,10.1899), (9.3509,9.3509), (13.929396,13.929396),
         (4.43708 ,4.43708) ,(2.23695,2.23695) ,(3.34379 ,3.34379), (1.89416,1.89416) , (4.72719,4.72719) ,
         (4.1657, 4.1657),  (0.535326,0.535326),(2.231424,2.231424),(0.27457,0.27457),(0.57916,0.57916) ,
         (4.410275,4.410275),(4.0934,4.0934 ),(3.12106 ,3.12106 ),(5.367372,5.367372),(5.897759,5.897759),
         (5.228994,5.228994),(0.084174,0.084174),(4.875925,4.875925),(4.38531,4.38531 ),(3.00054,3.00054 ),
         (1.454085,1.454085),(4.075335,4.075335),(1.616332,1.616332),(2.23991,2.23991 ),(4.40025,4.40025 ),
         (1.506965,1.506965),(0.994074,0.994074),(3.301525,3.301525),(1.24586,1.24586 ),(2.724975,2.724975),
         (4.92365,4.92365 ),(3.3054,3.3054),(24.892625,24.892625),(21.6432,21.6432 ),(16.927768,16.927768),
         (4.494695,4.494695),(3.489255,3.489255),(4.23843 ,4.23843),(2.379335,2.379335),(3.699805,3.699805)])

In [5]:
bounds = [(0,25),(0,25),(0,25),(0,25),(0,25),(0,25),(0,25),(0,25),(0,25),(0,25),
         (0,25),(0,25),(0,25),(0,25),(0,25),(0,25),(0,25),(0,25),(0,25),(0,25),
         (0,25),(0,25),(0,25),(0,25),(0,25),(0,25),(0,25),(0,25),(0,25),(0,25),
         (0,25),(0,25),(0,25),(0,25),(0,25),(0,25),(0,25),(0,25),(0,25),(0,25),
         (0,25),(0,25),(0,25),(0,25),(0,25),(0,25),(0,25),(0,25),(0,25),(0,25)]

bounds_left_springs = [  (0,25),   (0,25) ,   (0,25),   (0,25) ,   (0,25),
        (21.395675,21.395675),  (19.387975,19.387975),  (10.1899 ,10.1899 ) ,   (9.3509,9.3509)  ,  (13.929396,13.929396),
         (4.43708,4.43708) ,   (2.23695,2.23695) ,   (3.34379,3.34379) ,   (1.89416,1.89416) ,   (4.72719,4.72719) ,
         (4.1657,4.1657)  ,   (0,25),   (2.231424,2.231424),   (0,25) ,   (0.57916,0.57916) ,
         (0,25),   (4.0934,4.0934)  ,   (0,25) ,   (5.367372,5.367372),   (5.897759,5.897759),
         (5.228994,5.228994),   (0.084174,0.084174),   (4.875925,4.875925),   (0,25) ,   (3.00054,3.00054) ,
         (0,25),   (4.075335,4.075335),   (0,25),   (2.23991,2.23991) ,   (0,25) ,
         (0,25),   (0,25),   (0,25),   (0,25) , (0,25),
         (4.92365,4.92365) ,   (3.3054,3.3054)  ,  (24.892625,24.892625),  (21.6432,21.6432)  ,  (16.927768,16.927768),
         (4.494695,4.494695),   (3.489255,3.489255),   (4.23843,4.23843) ,   (2.379335,2.379335),   (3.699805,3.699805)]

In [5]:
bounds_minimum_important = [  (5.627202,5.627202), (4.90473,4.90473),(0.826185,0.826185),   (0,25),   (0,25),
        (21.395675,21.395675), (19.387975,19.387975), (10.1899,10.1899), (9.3509,9.3509), (13.929396,13.929396),
         (0,25) ,(0,25) ,(0,25), (1.89416,1.89416) , (4.72719,4.72719) ,
         (0,25),  (0.535326,0.535326),(0,25),(0.27457,0.27457),(0,25) ,
         (4.410275,4.410275),(4.0934,4.0934 ),(3.12106 ,3.12106 ),(5.367372,5.367372),(0,25),
         (5.228994,5.228994),(0,25),(4.875925,4.875925),(0,25),(0,25),
         (0,25),(0,25),(1.616332,1.616332),(2.23991,2.23991 ),(4.40025,4.40025 ),
         (1.506965,1.506965),(0,25),(0,25),(0,25),(0,25),
         (4.92365,4.92365 ),(3.3054,3.3054),(24.892625,24.892625),(21.6432,21.6432 ),(16.927768,16.927768),
         (4.494695,4.494695),(3.489255,3.489255),(0,25),(2.379335,2.379335),(0,25)]

bounds_maximum_important = [  (5.627202,5.627202), (0,25),(0,25),   (0,25),   (0,25),
        (21.395675,21.395675), (19.387975,19.387975), (10.1899,10.1899), (9.3509,9.3509), (13.929396,13.929396),
         (4.43708 ,4.43708) ,(0,25) ,(3.34379 ,3.34379), (0,25) , (0,25) ,
         (4.1657, 4.1657),  (0,25),(0,25),(0.27457,0.27457),(0,25) ,
         (4.410275,4.410275),(0,25 ),(0,25 ),(0,25),(5.897759,5.897759),
         (5.228994,5.228994),(0.084174,0.084174),(4.875925,4.875925),(0,25 ),(3.00054,3.00054 ),
         (0,25),(4.075335,4.075335),(1.616332,1.616332),(0,25 ),(4.40025,4.40025 ),
         (1.506965,1.506965),(0.994074,0.994074),(0,25),(0,25 ),(0,25),
         (4.92365,4.92365 ),(3.3054,3.3054),(24.892625,24.892625),(21.6432,21.6432 ),(16.927768,16.927768),
         (4.494695,4.494695),(3.489255,3.489255),(0,25),(2.379335,2.379335),(3.699805,3.699805)]

In [10]:
#23 4 31 3 39 34 20 38 40 15 5 14 24 17 18 29 2 22 48 12(max)
#40 4 27 30 5 48 39 50 16 12 11 32 18 38 13 25 37 29 20 31(min)
#2 3 4 5 11 12 13 14 15 16 17 18 20 22 23 24 25 27 29 30 31 32 34 37 38 39 40 48 50(zusammenfassung)
bounds_max_min_important = [(5.627202,5.627202), (0,25),(0,25),   (0,25),   (0,25),
        (21.395675,21.395675), (19.387975,19.387975), (10.1899,10.1899), (9.3509,9.3509), (13.929396,13.929396),
         (0,25) ,(0,25) ,(0,25), (0,25) , (0,25) ,
         (0,25),  (0,25),(0,25),(0.27457,0.27457),(0,25) ,
         (4.410275,4.410275),(0,25 ),(0,25 ),(0,25),(0,25),
         (5.228994,5.228994),(0,25),(4.875925,4.875925),(0,25 ),(0,25 ),
         (0,25),(0,25),(1.616332,1.616332),(0,25 ),(4.40025,4.40025 ),
         (1.506965,1.506965),(0,25),(0,25),(0,25 ),(0,25),
         (4.92365,4.92365 ),(3.3054,3.3054),(24.892625,24.892625),(21.6432,21.6432 ),(16.927768,16.927768),
         (4.494695,4.494695),(3.489255,3.489255),(0,25),(2.379335,2.379335),(0,25)]

In [6]:
#Function for minimum only
def function(stiffness):
    stiffness_array = []
    for i in range(0,50):
         stiffness_array.append(stiffness[i])
    stiffness_array = np.reshape(stiffness_array,(1,50))
    min_value = model.predict(stiffness_array)
    abs_min_value = np.abs(min_value)
    
    return abs_min_value

In [145]:
#Function
def function(stiffness):
    #stiffness = np.reshape(1,50)
    stiffness_array = []
    for i in range(0,50):
         stiffness_array.append(stiffness[i])
    stiffness_array = np.reshape(stiffness_array,(1,50))
    ele_array = model.predict(stiffness_array)
    min_value = np.min(ele_array)
    abs_min_value = np.abs(min_value)
    
    return abs_min_value

In [33]:
#Function Julius
def function1(stiffness):
    #stiffness = np.reshape(1,50)
    stiffness_array = []
    for i in range(0,50):
         stiffness_array.append(stiffness[i])
    stiffness_array = np.reshape(stiffness_array,(1,50))
    return np.max(np.abs(model.predict(stiffness_array)))

In [6]:
#Function lp norm
#LP=4 Norm
def function(stiffness):
    stiffness_array = []
    for i in range(0,50):
         stiffness_array.append(stiffness[i])
    stiffness_array = np.reshape(stiffness_array,(1,50))
    return np.linalg.norm(model.predict(stiffness_array)*scipy.pi/180.0, 4,axis=1)

In [7]:
def callbackF(param,convergence=0):
    np.save('template.npy',param)
    np.save('template_result.npy',function(param))
    print(param,function(param))   

In [8]:
result = differential_evolution(function,bounds,disp=True,callback=callbackF)
#np.save('end_result.npy',result.stiffness)
result.stiffness, result.fun

differential_evolution step 1: f(x)= 2.8847
[ 10.24212191   3.25982951   0.55944359   8.12224765  11.39817543
   2.72141667  17.73309486   6.18718519   3.41811092   2.98380329
   0.88255155  11.44828355  17.33640463  11.40904343   7.0997486
  19.39781202  12.68568568  17.59961808   3.65490021   2.04742342
   4.65232609   9.08566506   8.95359088  16.13705154  17.98476228
  18.63610508   0.42082509   4.44241873   4.62811465   0.89717477
  11.7955991   22.16527254  18.54497858  24.66237941   6.13552143
   4.20073311   9.90159687  12.02605381  11.33029506   5.81356107
   2.66988891  23.96847311  24.3422359    6.87645597  12.48626398
   1.12773333  10.16925273  15.63575086   0.96021833  12.0863679 ] [ 2.8846988]
differential_evolution step 2: f(x)= 2.87806
[ 22.82636442   5.06955265   3.151001     4.0540106    5.48057286
   6.61886078   7.36523968   4.29190465  10.06082428   2.59877517
   7.57814756   6.74759861  22.2294725   13.23769297   0.27764186
  17.65931869   4.37759045   4.50416382 

differential_evolution step 13: f(x)= 2.75956
[  1.00875888e+01   5.29239904e-03   8.40109653e-01   9.50339972e-01
   9.32257824e+00   6.00348413e+00   1.88076884e+01   2.25928871e+01
   1.98426527e+01   2.06123407e+01   2.14955565e+01   1.84413458e+00
   2.04483496e+01   5.58065023e-01   4.35637533e+00   1.24835006e+01
   6.06099547e-01   3.39372450e+00   3.32326314e+00   5.66348031e+00
   1.40205909e+01   2.25026913e+01   1.99554067e+00   1.42442936e+01
   2.44056705e+01   2.99225260e+00   2.12071044e+01   2.10687157e+01
   1.99650985e+01   3.16872501e+00   1.13569473e+01   2.28716230e+01
   1.95720192e+01   2.44774168e+01   2.36741795e+00   1.48850096e+01
   2.70308074e+00   1.52275529e+01   1.68490627e+00   4.92890713e+00
   2.06866651e+01   1.56660527e+01   1.36763597e+01   1.37866576e+01
   7.18680683e+00   1.26879433e+01   1.44736678e+01   1.81758626e+01
   1.28495138e+01   1.31078459e+01] [ 2.75955756]
differential_evolution step 14: f(x)= 2.75956
[  1.00875888e+01   5.29239904

differential_evolution step 24: f(x)= 2.71928
[  8.77849938  10.77081606   3.07164775   4.39010302  18.26927572
   3.33532924  15.99837897  13.5160888   23.20276994  23.1986122
   7.04092283  11.24232075  12.38043869   2.97758461   6.09656131
  18.94186971   0.22797095  10.38318298   2.92070471   5.49020258
  14.1700593   16.20267201  16.37666637  23.87464497  24.95720054
  14.71275628   3.28286422   9.31253837  22.56156592   4.39929745
  16.27778714  14.28074062  19.0441319   24.8895936    2.28013464
   6.14299811   0.17591409   7.33016362  19.33728669   9.54950419
   9.24386998  22.28364553  10.66163971   8.94425489  18.65833542
   1.53127425  10.1447215   13.20466921   5.19303798  17.28741537] [ 2.71927617]
differential_evolution step 25: f(x)= 2.71928
[  8.77849938  10.77081606   3.07164775   4.39010302  18.26927572
   3.33532924  15.99837897  13.5160888   23.20276994  23.1986122
   7.04092283  11.24232075  12.38043869   2.97758461   6.09656131
  18.94186971   0.22797095  10.383182

differential_evolution step 36: f(x)= 2.71778
[  3.52025968  10.63763586   3.96777459   3.16785869  18.53608709
  14.25403354   8.41149659  22.83610618   1.42580006  18.00935717
  12.11747952  11.03859479   8.55841423   3.54293853   4.32398529
  23.38960485   1.78237136   9.98146304   5.17760744  14.0443824
   7.34729536  13.63656314   1.89935635  12.3767027   24.91695547
  13.98208263   1.57587056  21.2139681   21.03283862   8.64236695
  15.87096972  13.95270125  19.04815562  19.2617209    2.75264797
   7.61441846   2.52920554  11.33331661  14.00358169  15.50019727
  13.90396559  19.71516936  20.75143271  12.23467562  23.86397409
   3.39177125   4.49267642  20.19226238   5.65452696  22.63402618] [ 2.71778204]
differential_evolution step 37: f(x)= 2.70544
[  3.45601508   2.35761268   3.68392979   0.18379533  17.87075886
  12.41669822  12.42678095   0.67112028   0.7393889   22.13221893
   5.67750737   2.76289597  12.5155083    2.03801626   3.69492624
  18.10172045   3.19737715  14.46400

AttributeError: stiffness

In [36]:
a = np.ndarray(shape=(1,50))

In [37]:
b = model.predict(a)

In [45]:
template = np.load('template.npy')
template = np.reshape(template,(1,50))

In [47]:
predict = model.predict(template)

In [133]:
y_train = np.load('y_train.npy')

In [136]:
np.amax(y_train,axis=1)

array([ 68.46158102,  67.39817136,  65.8024839 ,  70.62105895,
        69.03453882,  62.97608309,  70.96827138,  71.0209835 ,
        66.7174975 ,  72.72839772,  69.66708423,  75.09299455,
        81.71409483,  69.2167394 ,  82.02750274,  65.93426419,
        73.72706316,  85.38159767,  66.53873466,  64.95164157,
        63.56508371,  82.52998673,  71.45299367,  68.41116074,
        76.11400534,  71.73202412,  76.94708597,  69.03110107,
        72.49463094,  63.55305159,  74.06854601,  68.64148977,
        73.06701578,  77.72516266,  76.44689382,  66.97360963,
        72.70032279,  76.98948485,  76.40678677,  72.5536456 ,
        73.90926374,  78.3571351 ,  73.89952346,  78.54621118,
        71.21922689,  74.4283635 ,  77.72745449,  79.84166875,
        72.42473009,  80.45645247,  64.85710354,  76.18218731,
        72.0173571 ,  72.05574527,  72.11533288,  73.61075273,
        78.44651652,  74.83229875,  74.20319109,  65.7440422 ,
        67.71960068,  75.76736587,  82.09396584,  76.92

In [137]:
np.amin(y_train,axis=1)

array([-75.2293585 , -74.0903184 , -69.32846617, -69.67739747,
       -88.80043684, -70.14607694, -82.45321038, -75.23680695,
       -67.47208291, -85.49332444, -61.29158718, -75.86018503,
       -76.88062287, -78.2648889 , -81.19900577, -73.15181354,
       -70.39359471, -72.06319372, -80.76871446, -72.31300332,
       -75.15659286, -75.10674553, -70.32541273, -70.51334289,
       -75.79429489, -77.28684994, -76.17072816, -76.28818451,
       -72.08267429, -72.02136781, -76.80384652, -79.87432735,
       -71.20089224, -73.56319723, -64.0647029 , -74.89933481,
       -78.15258917, -74.95720355, -70.38729217, -73.22228734,
       -69.45738167, -72.92263042, -75.94326391, -64.90637791,
       -72.57484504, -67.96941028, -72.92893295, -55.94079162,
       -77.19861444, -75.34051231, -82.49331743, -70.90180827,
       -71.87984723, -79.10369911, -72.18523374, -76.29162225,
       -72.17549345, -77.37680432, -73.72591725, -82.91902507,
       -66.13021576, -69.71521268, -75.40869429, -67.26

In [7]:
spring_stiffness = np.load('Desktop/test_srpings/test1/template.npy')

In [6]:
np.load('Desktop/test_srpings/test1/template_result.npy')

array(40.320438385009766, dtype=float32)

In [10]:
shear_angle = model.predict(spring_stiffness.reshape(1,50))

In [12]:
np.min(shear_angle)

-93.770248

In [17]:
s = np.array([ 23.31664536,   8.46647002,  17.23769945,  15.83489492,  11.30297676,
   6.38401436,  24.91232368,  16.27891942,   5.61173021,  20.05647702,
  18.97558314,  13.77709173,   4.36760799,   2.42455999,   1.45040813,
  22.5912951,    7.71909965,   9.63054525,   5.17853349,   4.88169416,
  15.8296757,   11.81563585,  20.76948982,   7.37153997,   5.94863316,
  13.07570081,   5.07311575,   0.96157985,  11.03489463,   8.24527195,
  21.32135158,  10.83217054,   0.10071238,  17.34314975,   7.00860745,
  24.76900646,   2.9438388,   21.29851756,  23.4235725,    4.68520434,
   1.44965117,  20.57053736,   0.46078295,  13.95545533,  16.79497279,
   2.37815281,  22.60971556,   0.70092894,   0.75946481,   9.57981146]).reshape(1,50)

In [19]:
e = model.predict(s)

In [20]:
np.max(e)

45.58659

In [21]:
[  8.55673229e+00   5.39129894e+00   4.52736010e+00   4.38016155e-01
   5.66282861e+00   6.42451519e+00   1.42016226e+01   2.17014845e+01
   5.07399701e+00   2.37296991e+01   9.28387774e-01   6.46975176e+00
   8.69999014e+00   1.04753040e+00   1.21731599e+00   4.30932635e-03
   1.62132601e+00   4.10190328e+00   2.71847288e-01   8.16411149e-01
   6.12853130e+00   2.43125022e+00   1.61527168e+00   1.03940362e+01
   2.11058023e+00   1.58221986e-01   4.53627768e-01   1.20399920e+01
   6.24973467e+00   2.55463569e+00   3.67478472e+00   5.79628440e+00
   7.14486880e+00   4.41165881e+00   3.45660739e+00   5.54140165e+00
   1.73965563e-02   4.26215483e+00   6.06833218e+00   1.06983630e+01
   2.66998698e+00   5.68390287e+00   2.11301341e-01   2.45174668e+01
   2.34920712e+01   1.57042519e-01   1.81167446e+00   6.09670096e+00
   4.67481268e+00   3.40982442e+00]

-40.52713

In [20]:
#to predict the end result
stiffness = np.load('template.npy').reshape(1,50)
predict_angle = model.predict(stiffness)

In [22]:
np.min(predict_angle)

-38.815197

In [23]:
np.load('template_result.npy')

array(40.527130126953125, dtype=float32)

In [19]:
s.shape

(1, 50)

In [21]:
np.linalg.norm(s*scipy.pi/180.0, 4,axis=1)

array([ 0.76094885])

In [44]:
test_s = np.array([ 23.9966526,    2.4435013,    1.10288841,  24.24251822,   1.82451174,
   1.8442934,    6.79127947,   6.46766492,  12.68082938,   5.75907525,
  16.07657039,  20.35089368,   2.85844212,  16.22774706,   3.08934784,
  10.92166821,   0.41010935,   1.17991817,   3.98327368,  18.1551076,
  16.95506409,   6.22599509,  10.88139067,  21.39089833,   4.85048709,
  15.46111239,  24.09773868,   2.97943405,   1.52412454,  10.39971429,
   0.15033032,  13.15973401,   9.24857315,  22.70206117,  22.36441426,
   0.89718625,   0.45742022,   0.34819338,  23.7439138,    5.31642186,
   4.01793963,   9.03102486,  16.16406756,  11.84860139,  23.06481033,
   8.97636014,  24.33753864,  24.46893142,  16.51770597,   0.38387225]).reshape(1,50)

In [45]:
predict_s = model.predict(test_s)

In [53]:
np.min(predict_s)

-33.694912

In [21]:
import pandas

In [22]:
dataframe = pandas.read_csv("output_new.csv",delimiter=",",header=None)
X= dataframe.values
dataframe_y = pandas.read_csv("all_angle_value_sorted.csv",delimiter=",",header=None)
coefficient = (180/(np.pi))
y = dataframe_y.values*coefficient

In [31]:
X[304]

array([  5.627202,   4.90473 ,   0.826185,   0.30315 ,   2.098165,
        21.395675,  19.387975,  10.1899  ,   9.3509  ,  13.929396,
         4.43708 ,   2.23695 ,   3.34379 ,   1.89416 ,   4.72719 ,
         4.1657  ,   0.535326,   2.231424,   0.27457 ,   0.57916 ,
         4.410275,   4.0934  ,   3.12106 ,   5.367372,   5.897759,
         5.228994,   0.084174,   4.875925,   4.38531 ,   3.00054 ,
         1.454085,   4.075335,   1.616332,   2.23991 ,   4.40025 ,
         1.506965,   0.994074,   3.301525,   1.24586 ,   2.724975,
         4.92365 ,   3.3054  ,  24.892625,  21.6432  ,  16.927768,
         4.494695,   3.489255,   4.23843 ,   2.379335,   3.699805])